### PR TITLE
Add monitoring of others OS

### PR DESCRIPTION
**Pull request by ajabep**
Add :

* Multiple RPM based distro
* CentOS
* Arch Linux
* Some Pentest/DFIR OS 🙃

Requirements:

* First, merge #23

### CODE REVIEW

**Comment by niklasb** [comment]
please rebase on top of #23

**Comment by ajabep** [comment]
> please rebase on top of #23

Done :)

**Comment by ajabep** [comment]
> please rebase on top of #23

Better like that :)

**Comment by ajabep** [comment]
Hi,

I think that I haven't well understood the idea of this project: actually, your script was already incremental ;-). Thus, I thought it was made to update db.

Btw, I understand your judicious ideas about opt-in and opt-out. However, I'm not sure I understand why should `./get` pull only ubuntu and debian? Is it to limit the time taken by a "simple" `./get`? Is it for legacy? Moreover should not it display the list of available distros or download all distros?

I begin coding your idea: it will be simple to change later :)

> maybe it's time to set up a cloud service for this :)

Can I contact you on twitter? I got some ideas, and I'm sure discussing it can be interesting 😏
However, I'm not sure this PR is the right place for that.

**Comment by niklasb** [comment]
On Tue 18. Aug 2020 at 19:04, Ajabep <notifications@github.com> wrote:

>
>
>
> Hi,
>
>
>
> I think that I haven't well understood the idea of this project: actually,
> your script was already incremental ;-). Thus, I thought it was made to
> update db.
>

Yes I am aware and I am happy that you continued to support that scenario
well

>
>
>
> Btw, I understand your judicious ideas about opt-in and opt-out. However,
> I'm not sure I understand why should ./get pull only ubuntu and debian?
> Is it to limit the time taken by a "simple" ./get? Is it for legacy?
> Moreover should not it display the list of available distros or download
> all distros?
>

Yes, it takes a long time to pull “just” Ubuntu and almost as long again to
pull everything else. Initially it was viable to start it and have it
finished in a couple of minutes but that is no longer the case and I fear
that this might make it not as useful to a lot of people who don’t have a
DB already prepared.

>
>
>
> I begin coding your idea: it will be simple to change later :)
>
>
>
>
>
>
> maybe it's time to set up a cloud service for this :)
>
>
>
>
>
>
> Can I contact you on twitter? I got some ideas, and I'm sure discussing it
> can be interesting 😏
>

Sure no problem!

**Comment by ajabep** [comment]
(I stop here, will continue soon, but I have not finished. No need to review for now ;-) )
Moreover, I forgot to say: the bug on the script `./identify` on Ubuntu was introduced in #22, and will be fixed with #26 :)

**Comment by niklasb** [comment]
> Moreover should not it display the list of available distros or download all distros?

yes I like this idea: if `./get` is called without arguments, it could print a list of possible download categories like

```
$ ./get
Please specify libc categories to download:
  * ubuntu
  * debian
  * rpm
  * centos
  * arch
  ...

You may also specify "all" to download all categories available.

Example:

$ ./get ubuntu rpm arch
$ ./get all
```

**Comment by ajabep** [comment]
`apt-get` command works perfectly on a debian 10 slim, and should works for any debian-based OS :ok_hand:

**Pull request merged**
