### PR TITLE
Add Pwntools API

### PR DESCRIPTION
**Pull request by ajabep**
In order to add the ability to integrate this search engine in pwntools, these changes aims to add endpoints used by pwntools.

### CODE REVIEW

**Review by niklasb — APPROVED** [review]

**Comment by niklasb** [comment]
this doesn't make sense. the endpoint returns plaintext in some cases, and JSON in others. Please use the existing `/find` endpoint instead

**Comment by niklasb** [comment]
or maybe I am missing what this gives us

**Comment by ajabep** [comment]
Yes, exactly, it's possible to do the same thing using `/find` and parsing the JSON, and it's exactly what does the code. However, pwntools uses a `/hashes/HASHTYPE/HASH` path in order to get the download link to the `.so` file.  
Moreover, the ability to use a path instead of post parameters allows multiple ways to implement it when somebody else wanna implement the pwntools's *de facto* "API" (e.g. if somebody wanna implement a db using git, as what does currently pwntools).

Actually this endpoint is not indented to be used by humans, only by pwntools (or tools using the same *de facto* "API").

**Comment by niklasb** [comment]
But what you propose is not compatible with pwntools: it expects the libc
file to be returned directly, and not an URL. So seeing as the library will
have to be adapted anyways, I don’t  see why this be part of our API. There
is no upside

**Comment by niklasb** [comment]
Ah my mistake, it would actually work, but the base URL is hard coded so
pwntools has to be changed anyways. I suggest you propose a patch for
pwntools which uses the /find API instead, and if they are unwilling to
accept this (which I doubt) we can think about adding this as a
compatibility layer

**Pull request merged**
