### PR TITLE
Downloading of libc packages fails quietly rather than dying

### PR DESCRIPTION
**Pull request by mariuszskon**
Closes https://github.com/niklasb/libc-database/issues/41

I don't really know bash scripting so the code might not be ideal :sweat_smile:

### CODE REVIEW

**Comment by niklasb** [comment]
can you clarify what the implications of this are w.r.t. https://github.com/niklasb/libc-database/issues/43?

**Comment by mariuszskon** [comment]
> can you clarify what the implications of this are w.r.t. #43?

I do not believe that this PR causes the bug in #43, but rather it lets the downloader progress far enough that that issue is reached. This PR fixes timeouts regarding downloading a single particular libc instance, not touching anything else, while #43 is about getting the package locations for a "family" of libc afaik.

**Comment by niklasb** [comment]
thanks for analyzing this bug, I addressed it in 460851d300b802f71e9ef1ba4a9f5080ff7f4c37 along with #43

**Comment by mariuszskon** [comment]
Cheers

**Pull request closed without merging**
